on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: bae116447b0e414eb03a5f0f293c5dc6.azurecr.io
        username: ${{ secrets.acr_bae116447b0e414eb03a5f0f293c5dc6_username }}
        password: ${{ secrets.acr_bae116447b0e414eb03a5f0f293c5dc6_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.devcontainer" -f  ".devcontainer/Dockerfile" -t bae116447b0e414eb03a5f0f293c5dc6.azurecr.io/cisamples:${{ github.sha }} --label dockerfile-path=.devcontainer/Dockerfile
        docker push bae116447b0e414eb03a5f0f293c5dc6.azurecr.io/cisamples:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_cisamples_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep cisamplesab55 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace cisamplesab55`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: cisamplesab55
        container-registry-url: bae116447b0e414eb03a5f0f293c5dc6.azurecr.io
        container-registry-username: ${{ secrets.acr_bae116447b0e414eb03a5f0f293c5dc6_username }}
        container-registry-password: ${{ secrets.acr_bae116447b0e414eb03a5f0f293c5dc6_password }}
        secret-name: cisamplesdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: cisamplesab55
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          bae116447b0e414eb03a5f0f293c5dc6.azurecr.io/cisamples:${{ github.sha }}
        imagepullsecrets: |
          cisamplesdockerauth
